import {useMemo,useState} from 'react';import {Link} from 'react-router-dom';import {describeRoomCleaning,isValidCleaningSetting} from '@/lib/cleaning';import {supabase} from '@/lib/supabase';
export function LoginPage(){return <AuthForm mode="login"/>}export function SignupPage(){return <AuthForm mode="signup"/>}
function AuthForm({mode}:{mode:'login'|'signup'}){const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[msg,setMsg]=useState('');async function submit(e:React.FormEvent){e.preventDefault();const r=mode==='login'?await supabase.auth.signInWithPassword({email,password:pw}):await supabase.auth.signUp({email,password:pw});if(r.error)setMsg(r.error.message);else location.href='/app/home'}return <main className="mx-auto max-w-md p-6"><h1 className="mb-2 text-4xl font-semibold tracking-tight">{mode==='login'?'로그인':'회원가입'}</h1><p className="mb-8 text-zinc-600">생활관 청소 추첨을 시작하세요.</p><form onSubmit={submit} className="card space-y-4"><input className="w-full rounded-xl border p-3" placeholder="이메일" value={email} onChange={e=>setEmail(e.target.value)}/><input className="w-full rounded-xl border p-3" type="password" placeholder="비밀번호" value={pw} onChange={e=>setPw(e.target.value)}/><button className="btn w-full">{mode==='login'?'로그인':'가입하기'}</button>{msg&&<p className="text-sm text-red-600">{msg}</p>}<Link className="text-action" to={mode==='login'?'/signup':'/login'}>{mode==='login'?'계정 만들기':'이미 계정이 있어요'}</Link></form></main>}
export function HomePage(){return <Page title="오늘의 생활관"><div className="card"><p className="text-lg font-semibold">오후 9시에 내일 청소자를 추첨합니다.</p><p className="mt-2 text-zinc-600">오후 8시 50분 전까지 야간근무·부재 일정을 등록하세요.</p></div><AdminLinks/></Page>}
export function CalendarPage(){const[quick,setQuick]=useState(true);const days=Array.from({length:35},(_,i)=>i+1);return <Page title="캘린더"><div className="card mb-4 flex items-center justify-between"><span>야간근무 원터치 등록</span><button onClick={()=>setQuick(!quick)} className="btn">{quick?'켜짐':'꺼짐'}</button></div><div className="grid grid-cols-7 gap-2">{days.map(d=><button key={d} className="min-h-14 rounded-2xl bg-white text-sm ring-1 ring-zinc-100 active:bg-blue-50"><b>{d}</b>{quick&&d%6===0?<span className="block text-xs text-action">야근</span>:null}</button>)}</div></Page>}
export function CleaningSettingsPage(){const[f,setF]=useState(2);const[w,setW]=useState([1,5]);const preview=useMemo(()=>describeRoomCleaning(f,w),[f,w]);function toggle(d:number){if(f===7)return;setW(v=>v.includes(d)?v.filter(x=>x!==d):v.length<f?[...v,d]:v)}return <Page title="호실 청소 설정"><div className="card space-y-4"><div className="grid grid-cols-4 gap-2">{[0,1,2,3,4,5,6,7].map(x=><button className={`rounded-2xl p-3 ring-1 ${f===x?'bg-action text-white':'bg-white'}`} onClick={()=>{setF(x);setW(x===0?[]:x===7?[0,1,2,3,4,5,6]:[])}} key={x}>{x===0?'안 함':x===7?'매일':`주 ${x}회`}</button>)}</div>{f>0&&f<7&&<><p className="text-sm text-zinc-600">선택 {w.length}/{f}</p><div className="grid grid-cols-7 gap-2">{['월','화','수','목','금','토','일'].map((d,i)=><button key={d} onClick={()=>toggle(i)} className={`rounded-full p-3 ${w.includes(i)?'bg-action text-white':'bg-zinc-100'}`}>{d}</button>)}</div></>}<p className="rounded-2xl bg-parchment p-4">{preview}</p><button disabled={!isValidCleaningSetting(f,w)} className="btn w-full">저장</button></div></Page>}
export function DrawResultPage(){return <Page title="추첨 결과"><div className="card space-y-3"><p className="chip w-fit">샤세건 · 내일</p><h2 className="text-2xl font-semibold">내일 청소자가 선정되었습니다.</h2><p>샤세건: 김OO</p><p>호실 청소: 박OO</p><hr/><p className="text-sm text-zinc-600">제외: 이OO(야간근무), 최OO(휴가), 정OO(전날 청소)</p></div></Page>}
export function LeaderboardPage(){return <Page title="리더보드"><div className="card"><p>이번 주 1회 · 이번 달 3회 · 전체 12회</p><p className="mt-2 text-zinc-600">일반 사용자에게 현재 가중치는 숨김 처리됩니다.</p></div></Page>}
export function ProfilePage(){return <Page title="내 정보"><div className="card space-y-3"><p>PWA 설치 후 iOS/iPadOS 알림 권한을 요청할 수 있습니다.</p><button className="btn">웹푸시 활성화</button></div></Page>}
export function CreateRoomPage(){return <Page title="생활관 만들기"><div className="card"><input className="w-full rounded-xl border p-3" placeholder="생활관 이름"/><button className="btn mt-4 w-full">생성</button></div></Page>}
export function JoinPage(){return <Page title="초대 가입"><div className="card"><p>초대 정보를 확인한 뒤 생활관에 가입합니다.</p><button className="btn mt-4 w-full">가입하기</button></div></Page>}
export function SimplePage({title}:{title:string}){return <Page title={title}><div className="card">MVP 관리 기능 화면입니다. API 권한 검사는 서버에서 수행됩니다.</div></Page>}
function AdminLinks(){return <div className="card mt-4"><p className="mb-3 font-semibold">관리자 메뉴</p><div className="grid grid-cols-2 gap-2 text-action"><Link to="/app/admin/cleaning-settings">청소 설정</Link><Link to="/app/admin/invites">초대</Link><Link to="/app/admin/draw">수동 추첨</Link><Link to="/app/admin/logs">로그</Link></div></div>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <section className="p-5"><h1 className="mb-5 text-4xl font-semibold tracking-tight">{title}</h1>{children}</section>}
