"""initial schema
Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-11
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial_schema'; down_revision=None; branch_labels=None; depends_on=None
def uuid_pk(): return sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True)
def timestamps(): return [sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()')),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'))]
def upgrade():
    op.create_table('profiles',uuid_pk(),sa.Column('supabase_user_id',sa.String(128),nullable=False),sa.Column('email',sa.String(320),nullable=False),sa.Column('display_name',sa.String(80),nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true'),*timestamps(),sa.UniqueConstraint('supabase_user_id'))
    op.create_index('ix_profiles_supabase_user_id','profiles',['supabase_user_id'])
    op.create_table('rooms',uuid_pk(),sa.Column('name',sa.String(80),nullable=False),sa.Column('timezone',sa.String(64),nullable=False),sa.Column('draw_time',sa.Time(),nullable=False),sa.Column('reminder_time',sa.Time(),nullable=False),sa.Column('rotation_start_date',sa.Date(),nullable=False),sa.Column('base_zone',sa.String(40),nullable=False),sa.Column('allow_same_person',sa.Boolean(),server_default='false'),sa.Column('is_active',sa.Boolean(),server_default='true'),*timestamps())
    op.create_table('room_members',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('profile_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('profiles.id')),sa.Column('role',sa.String(16),nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true'),sa.Column('weight',sa.Numeric(6,2),server_default='100'),sa.Column('candidate_count',sa.Integer(),server_default='0'),sa.Column('not_selected_count',sa.Integer(),server_default='0'),sa.Column('incomplete_count',sa.Integer(),server_default='0'),*timestamps(),sa.UniqueConstraint('profile_id','is_active',name='uq_one_active_room_per_profile'))
    op.create_index('ix_room_members_room_role','room_members',['room_id','role'])
    op.create_table('room_invites',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('created_by_member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('token_hash',sa.String(128),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('max_uses',sa.Integer(),server_default='1'),sa.Column('used_count',sa.Integer(),server_default='0'),sa.Column('revoked',sa.Boolean(),server_default='false'),*timestamps(),sa.UniqueConstraint('token_hash'))
    op.create_index('ix_room_invites_room_id','room_invites',['room_id'])
    op.create_table('availability_events',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('event_type',sa.String(40),nullable=False),sa.Column('start_date',sa.Date(),nullable=False),sa.Column('end_date',sa.Date(),nullable=False),sa.Column('note',sa.Text()),*timestamps())
    op.create_index('ix_availability_events_room_id','availability_events',['room_id']); op.create_index('ix_availability_events_member_id','availability_events',['member_id'])
    op.create_table('room_cleaning_settings',sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id'),primary_key=True),sa.Column('room_cleaning_frequency',sa.Integer(),server_default='0'),sa.Column('room_cleaning_weekdays',postgresql.ARRAY(sa.Integer()),server_default='{}'),*timestamps())
    op.create_table('weekly_zone_overrides',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('week_start_date',sa.Date(),nullable=False),sa.Column('zone',sa.String(40),nullable=False),sa.Column('reason',sa.Text()),*timestamps(),sa.UniqueConstraint('room_id','week_start_date'))
    op.create_table('draw_runs',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('target_date',sa.Date(),nullable=False),sa.Column('run_type',sa.String(20),nullable=False),sa.Column('version',sa.Integer(),server_default='1'),sa.Column('zone',sa.String(40),nullable=False),sa.Column('is_active',sa.Boolean(),server_default='true'),sa.Column('reason',sa.Text()),sa.Column('completed_at',sa.DateTime(timezone=True)),*timestamps(),sa.UniqueConstraint('room_id','target_date','is_active',name='uq_active_draw_per_day'))
    op.create_index('ix_draw_runs_room_id','draw_runs',['room_id']); op.create_index('ix_draw_runs_target_date','draw_runs',['target_date'])
    op.create_table('draw_tasks',uuid_pk(),sa.Column('draw_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('draw_runs.id')),sa.Column('task_type',sa.String(40),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('duplicate_reason',sa.Text()),*timestamps())
    op.create_table('draw_candidates',uuid_pk(),sa.Column('draw_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('draw_runs.id')),sa.Column('member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('weight_snapshot',sa.Numeric(6,2)),sa.Column('probability_snapshot',sa.Numeric(8,6)),sa.Column('selected',sa.Boolean(),server_default='false'),*timestamps())
    op.create_table('draw_exclusions',uuid_pk(),sa.Column('draw_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('draw_runs.id')),sa.Column('member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('reasons',postgresql.ARRAY(sa.String())),*timestamps())
    op.create_table('cleaning_assignments',uuid_pk(),sa.Column('draw_task_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('draw_tasks.id'),unique=True),sa.Column('member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('status',sa.String(40),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('completed_by_member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('weight_delta',sa.Numeric(5,2),server_default='0'),*timestamps())
    op.create_table('push_subscriptions',uuid_pk(),sa.Column('profile_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('profiles.id')),sa.Column('endpoint',sa.Text(),nullable=False,unique=True),sa.Column('p256dh',sa.Text(),nullable=False),sa.Column('auth',sa.Text(),nullable=False),sa.Column('user_agent',sa.Text()),sa.Column('success_count',sa.Integer(),server_default='0'),sa.Column('failure_count',sa.Integer(),server_default='0'),sa.Column('is_active',sa.Boolean(),server_default='true'),*timestamps())
    op.create_table('audit_logs',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('actor_member_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('room_members.id')),sa.Column('action',sa.String(80),nullable=False),sa.Column('payload',postgresql.JSONB(),server_default='{}'),*timestamps())
    op.create_table('job_runs',uuid_pk(),sa.Column('room_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('rooms.id')),sa.Column('job_type',sa.String(40),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('success_count',sa.Integer(),server_default='0'),sa.Column('failure_count',sa.Integer(),server_default='0'),sa.Column('error',sa.Text()),*timestamps())
def downgrade():
    for t in ['job_runs','audit_logs','push_subscriptions','cleaning_assignments','draw_exclusions','draw_candidates','draw_tasks','draw_runs','weekly_zone_overrides','room_cleaning_settings','availability_events','room_invites','room_members','rooms','profiles']: op.drop_table(t)
